version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pgext:latest
    hostname: app
    network_mode: "bridge"
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./public:/srv/public
      - ./build:/srv/pgext/build
      - ./app:/srv/app
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  redis:
    image: bitnami/redis:5.0.5
    restart: always
    container_name: redis_ext
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami/redis/data
